app.py
from flask import Flask
from routes import pages

def create_app():
    app = Flask(__name__)
    app.register_blueprint(pages)
    return app


#app = create_app()

#app.run(debug = True)

routes.py
from flask import  Blueprint,render_template, request, redirect, url_for
import datetime
from collections import defaultdict
from pymongo import MongoClient
from dotenv import load_dotenv
import os
load_dotenv()

pages = Blueprint("habits", __name__, template_folder="template", static_folder="static")

#habits = ["Test Habit", "Second Habit"]
#completions = defaultdict(list)
MONGO_URL = os.environ.get("MONGO_URL")
mongo_client= MongoClient(MONGO_URL)
db = mongo_client["habit_tracker"]
habits = db["habits"]
completions = db['completions']


@pages.context_processor
def add_date_range():
    def date_range(start):
        dates = [start+ datetime.timedelta(days=diff) for diff in range(-3,4)] 
        return dates
    return {"date_range":date_range}



@pages.route('/')
def index():
    date = request.args.get("date")

    if date:
        selected_date = datetime.date.fromisoformat(date) 
    else:
        selected_date = datetime.date.today()

    habits_contents = [habit["habit"] for habit in habits.find({})]
    completions_content = [completion["habit"] for completion in completions.find({"date":datetime.datetime.combine(selected_date,datetime.time())})]

    return render_template("index.html", habits = habits_contents ,title = "Habit Tracker - Home", selected_date=selected_date, completions=completions_content)

@pages.route("/add", methods=["POST","GET"])
def add_habit():

    if request.method == "POST":    
        habit = request.form.get("habit")
        #habits.append(habit)
        habits.insert_one({"habit":habit})

        return redirect(url_for("habits.index", date= datetime.date.today()))
    else:
        return render_template("add_habit.html", title = "Habit Tracker - Add Habit", selected_date=datetime.date.today())


@pages.route("/complete", methods = ["POST"])
def complete():
    date_string  = request.form.get("date")
    habit  = request.form.get("habitName")
    date = datetime.date.fromisoformat(date_string)
    #completions[date].append(habit)
    completions.insert_one({"date":datetime.datetime.combine(date,datetime.time()), "habit":habit})
    return redirect(url_for("habits.index", date= date_string))

templates/add_habit.html
{% extends "layout.html" %}

{% block main_content %}
    <form class="form" method="POST">
        <textarea name="habit" id="habit" class="form__input" rows="3" placeholder="Add a new daily habit"></textarea>
        <button type="submit" class="form__button">Add</button>
    </form>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block main_content %}
    <section class="habit-list">
        {% for habit in habits %}
            {% set completed = habit in completions %}
            {% if completed %}
                <div class="habit completed">
                    <p class="habit__name">
                        {{ habit }}
                    </p>
                    <img class="habit__icon" src="/static/checkmark.svg" alt="the checkmark icon">
                </div>
            {% else %}
                <div class="habit">
                    <form method="POST" class="habit__form" action="{{url_for('habits.complete')}}">
                        <input type="hidden" name="habitName" value="{{habit}}">
                        <input type="hidden" name="date" value="{{selected_date}}">
                        <button type="submit" class="habit__button">
                            {{habit}}
                        </button>
                    </form>
                </div>
            {% endif %}
        {% endfor %}
    </section>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge" />
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('habits.static', filename='/css/main.css') }}">
    
    {% block head_content %} {% endblock %}
</head>
<body>
    <header class="header">
        <h1 class="header__logo"><a href="{{ url_for('habits.index') }}" class="header__link">Habits</a></h1>
        {% if "add" not in request.endpoint %}
            <a href="{{ url_for('habits.add_habit') }}" class="header__link">+ Add new</a>
        {% endif %}
    </header>

    <main class="main">
        <section class="dates">
            {% for date in date_range(selected_date) %}
                <a  class="dates__link {{ 'dates__link--current' if loop.index0 == 3 else '' }}" href="{{ url_for('habits.index', date=date) }}">
                    <time class="date" datetime="{{ date }}">
                        <span>{{ date.strftime("%a") }}</span>
                        <span>{{ date.strftime("%d") }}</span>
                    </time>
                </a>
            {% endfor %}
        </section>
        {% block main_content %}

        {% endblock %}
    </main>
</body>
</html>